const stockCategories = [
  "Growth",
  "Value",
  "Dividend",
  "Cyclical",
  "Defensive",
];

const STOCK = {
  "Large Cap": [...stockCategories],
  "Mid Cap": [...stockCategories],
  "Small Cap": [...stockCategories],
  "Micro Cap": [...stockCategories],
};

const MUTUAL_FUND = {
  Equity: [
    "Large Cap Fund",
    "Large & Mid Cap Fund",
    "Mid Cap Fund",
    "Small Cap Fund",
    "Multi Cap Fund",
    "Flexi Cap Fund",
    "Focused Fund",
    "Dividend Yield Fund",
    "Value Fund",
    "Contra Fund",
    "Sectoral Fund",
    "Thematic Fund",
    "ELSS",
  ],
  Debt: [
    "Overnight Fund",
    "Liquid Fund",
    "Ultra Short Duration Fund",
    "Low Duration Fund",
    "Money Market Fund",
    "Short Duration Fund",
    "Medium Duration Fund",
    "Medium to Long Duration Fund",
    "Long Duration Fund",
    "Dynamic Bond Fund",
    "Corporate Bond Fund",
    "Credit Risk Fund",
    "Banking & PSU Fund",
    "Gilt Fund",
    "Gilt Fund with 10 year constant duration",
    "Floater Fund",
  ],
  Hybrid: [
    "Conservative Hybrid Fund",
    "Balanced Hybrid Fund",
    "Aggressive Hybrid Fund",
    "Dynamic Asset Allocation Fund",
    "Multi Asset Allocation Fund",
    "Arbitrage Fund",
    "Equity Savings Fund",
  ],
  "Solution Oriented": ["Retirement Fund", "Children's Fund"],
  Other: ["Index Fund", "FoF Domestic", "FoF Overseas"],
};

const INDEX = {
  "Equity Index": {
    BroadMarket: [
      "Nifty 50",
      "Nifty Next 50",
      "Nifty 100",
      "Nifty 200",
      "Nifty Total Market",
      "Nifty 500",
      "Nifty 500 Multicap 50:25:25",
      "Nifty500 LargeMidSmall Equal-Cap Weighted",
    ],
    LargeCap: [
      "Nifty50 Shariah",
      "Nifty100 Liquid 15",
      "Nifty100 ESG",
      "Nifty100 Enhanced ESG",
    ],
    MidCap: [
      "Nifty Midcap150",
      "Nifty Midcap 50",
      "Nifty Midcap Select",
      "Nifty Midcap 100",
      "Nifty MidSmallcap 400",
      "Nifty MidSmallcap400 50:50",
      "Nifty MidSmall Financial Services",
      "Nifty MidSmall Healthcare",
      "Nifty MidSmall IT & Telecom",
      "Nifty MidSmall India Consumption",
    ],
    SmallCap: [
      "Nifty Smallcap 500",
      "Nifty Smallcap 250",
      "Nifty Smallcap 50",
      "Nifty Smallcap 100",
      "Nifty Microcap 250",
    ],
    Sectoral: [
      "Nifty Bank",
      "Nifty Cement",
      "Nifty Auto",
      "Nifty Chemicals",
      "Nifty Financial Services",
      "Nifty Financial Services 25/50",
      "Nifty Financial Services Ex-Bank",
      "Nifty FMCG",
      "Nifty Healthcare",
      "Nifty IT",
      "Nifty Media",
      "Nifty Metal",
      "Nifty Pharma",
      "Nifty Private Bank",
      "Nifty PSU Bank",
      "Nifty Realty",
      "Nifty REITs & Realty",
      "Nifty Consumer Durables",
      "Nifty Oil and Gas",
      "Nifty Infrastructure",
      "Nifty Services Sector",
      "Nifty Transportation & Logistics",
    ],
    Thematic: [
      "Nifty Capital Markets",
      "Nifty Conglomerate 50",
      "Nifty Core Housing",
      "Nifty CPSE",
      "Nifty EV & New Age Automotive",
      "Nifty Housing",
      "Nifty India Consumption",
      "Nifty India Defence",
      "Nifty India Digital",
      "Nifty India Infrastructure & Logistics",
      "Nifty India Internet",
      "Nifty India Manufacturing",
      "Nifty India New Age Consumption",
      "Nifty India Railways PSU",
      "Nifty India Tourism",
      "Nifty IPO",
      "Nifty MNC",
      "Nifty Mobility",
      "Nifty PSE",
      "Nifty REITs & InvITs",
      "Nifty Rural",
      "Nifty Non-Cyclical Consumer",
      "Nifty Shariah 25",
      "Nifty500 Shariah",
      "Nifty500 Multicap India Manufacturing 50:30:20",
      "Nifty500 Multicap Infrastructure 50:30:20",
      "Nifty SME EMERGE",
      "Nifty Waves",
      "Nifty100 ESG Sector Leaders",
      "India Vix",
    ],
  },
  "Bond Index": [
    "Government Securities Index",
    "Corporate Bond Index",
    "Composite Bond Index",
  ],
  "Commodity Index": ["Gold", "Silver", "Crude Oil", "Multi Commodity"],
  "International Index": [
    "MSCI World",
    "MSCI Emerging Markets",
    "S&P 500",
    "NASDAQ 100",
  ],
};

const ETF = {
  "Debt ETF": [
    "Gilt ETF",
    "10 Year Gilt ETF",
    "5 Year Gilt ETF",
    "Corporate Bond ETF",
    "PSU Bond ETF",
    "Liquid ETF",
  ],
  "Commodity ETF": ["Gold ETF", "Silver ETF"],
  "International ETF": ["NASDAQ 100", "S&P 500", "Hang Seng", "Nikkei 225"],
};

const BOND = {
  Government: [
    "Central Government Securities",
    "State Development Loans",
    "Treasury Bills",
    "Sovereign Gold Bond",
    "Floating Rate Bonds",
    "Capital Indexed Bonds",
    "Inflation Indexed Bonds",
  ],
  Corporate: [
    "AAA Rated",
    "AA Rated",
    "A Rated",
    "BBB Rated (Investment Grade)",
    "BB and Below (High Yield)",
    "Convertible Debentures",
    "Non-Convertible Debentures",
    "Secured Bonds",
    "Unsecured Bonds",
    "Subordinated Bonds",
    "Zero Coupon Bonds",
    "Perpetual Bonds",
  ],
  Municipal: ["General Obligation", "Revenue Bond"],
  PSU: ["PSU Bonds (Tax-Free)", "PSU Bonds (Taxable)"],
  International: ["Masala Bonds", "Foreign Currency Bonds"],
};

const SECTORS = {
  "Basic Materials": [
    "Chemicals",
    "Construction Materials",
    "Metals & Mining",
    "Paper & Forest Products",
    "Steel",
    "Aluminum",
    "Cement",
  ],
  "Consumer Cyclical": [
    "Auto Components",
    "Automobiles",
    "Consumer Durables",
    "Apparel",
    "Hotels, Restaurants & Leisure",
    "Household Durables",
    "Leisure Products",
    "Textiles",
    "Retail",
    "E-commerce",
  ],
  "Consumer Defensive": [
    "Beverages",
    "Food Products",
    "Tobacco",
    "Household Products",
    "Personal Products",
    "FMCG",
  ],
  Energy: [
    "Oil & Gas Exploration & Production",
    "Oil & Gas Refining & Marketing",
    "Oil & Gas Equipment & Services",
    "Coal",
    "Renewable Energy",
    "Power Generation",
    "Power Distribution",
  ],
  "Financial Services": [
    "Banks - Public Sector",
    "Banks - Private Sector",
    "Banks - Small Finance",
    "Non-Banking Financial Companies (NBFC)",
    "Housing Finance Companies",
    "Asset Management",
    "Insurance - Life",
    "Insurance - General",
    "Insurance - Health",
    "Stock Exchanges",
    "Brokers & Securities",
    "Financial Conglomerates",
    "Microfinance",
  ],
  Healthcare: [
    "Pharmaceuticals",
    "Biotechnology",
    "Medical Devices",
    "Healthcare Providers",
    "Hospitals",
    "Diagnostics",
    "Healthcare Equipment",
    "Contract Research Organizations (CRO)",
  ],
  Industrials: [
    "Aerospace & Defense",
    "Building Products",
    "Construction & Engineering",
    "Electrical Equipment",
    "Industrial Conglomerates",
    "Machinery",
    "Trading Companies",
    "Commercial Services",
    "Airlines",
    "Marine",
    "Road & Rail",
    "Transportation Infrastructure",
    "Logistics",
  ],
  "Real Estate": [
    "Real Estate Development",
    "Real Estate Investment Trusts (REITs)",
    "Real Estate Services",
  ],
  Technology: [
    "IT Services",
    "Software - Application",
    "Software - Infrastructure",
    "Semiconductors",
    "Electronics",
    "Computer Hardware",
    "IT Consulting",
    "Fintech",
    "Edtech",
  ],
  "Communication Services": [
    "Telecom Services",
    "Media",
    "Entertainment",
    "Broadcasting",
    "Publishing",
    "Internet Services",
  ],
  Utilities: [
    "Electric Utilities",
    "Gas Utilities",
    "Water Utilities",
    "Renewable Utilities",
  ],
};

const AMCs = [
  "SBI Mutual Fund",
  "ICICI Prudential Mutual Fund",
  "HDFC Mutual Fund",
  "Nippon India Mutual Fund",
  "Aditya Birla Sun Life Mutual Fund",
  "Kotak Mahindra Mutual Fund",
  "Axis Mutual Fund",
  "UTI Mutual Fund",
  "DSP Mutual Fund",
  "Franklin Templeton Mutual Fund",
  "IDFC Mutual Fund",
  "Invesco Mutual Fund",
  "Mirae Asset Mutual Fund",
  "Tata Mutual Fund",
  "Sundaram Mutual Fund",
  "PGIM India Mutual Fund",
  "Edelweiss Mutual Fund",
  "HSBC Mutual Fund",
  "IDBI Mutual Fund",
  "LIC Mutual Fund",
  "Mahindra Manulife Mutual Fund",
  "Motilal Oswal Mutual Fund",
  "Navi Mutual Fund",
  "PPFAS Mutual Fund",
  "Quantum Mutual Fund",
  "Quant Mutual Fund",
  "Shriram Mutual Fund",
  "Union Mutual Fund",
  "WhiteOak Capital Mutual Fund",
  "Zerodha Mutual Fund",
  "Groww Mutual Fund",
  "Bajaj Finserv Mutual Fund",
  "Baroda BNP Paribas Mutual Fund",
  "Bandhan Mutual Fund",
  "BOI AXA Mutual Fund",
  "Canara Robeco Mutual Fund",
  "JM Financial Mutual Fund",
  "ITI Mutual Fund",
  "NJ Mutual Fund",
  "Old Bridge Mutual Fund",
  "360 ONE Mutual Fund",
  "Samco Mutual Fund",
  "Trust Mutual Fund",
];

const financialData = {
  classes: [
    {
      name: "STOCK",
      sectorRequired: true,
      industryRequired: true,
      amcRequired: false,
      categories: [
        { name: "Large Cap", subcategories: [...STOCK["Large Cap"]] },
        { name: "Mid Cap", subcategories: [...STOCK["Mid Cap"]] },
        { name: "Small Cap", subcategories: [...STOCK["Small Cap"]] },
        { name: "Micro Cap", subcategories: [...STOCK["Micro Cap"]] },
      ],
    },
    {
      name: "MUTUAL FUND",
      sectorRequired: false,
      industryRequired: false,
      amcRequired: true,
      categories: [
        { name: "Equity", subcategories: [...MUTUAL_FUND.Equity] },
        { name: "Debt", subcategories: [...MUTUAL_FUND.Debt] },
        { name: "Hybrid", subcategories: [...MUTUAL_FUND.Hybrid] },
        {
          name: "Solution Oriented",
          subcategories: [...MUTUAL_FUND["Solution Oriented"]],
        },
        { name: "Other", subcategories: [...MUTUAL_FUND.Other] },
      ],
    },
    {
      name: "ETF",
      sectorRequired: false,
      industryRequired: false,
      amcRequired: true,
      categories: [
        {
          name: "Equity ETF",
          subcategories: [
            ...INDEX["Equity Index"].BroadMarket,
            ...INDEX["Equity Index"].LargeCap,
            ...INDEX["Equity Index"].MidCap,
            ...INDEX["Equity Index"].SmallCap,
            ...INDEX["Equity Index"].Sectoral,
            ...INDEX["Equity Index"].Thematic,
          ],
        },
        { name: "Debt ETF", subcategories: [...ETF["Debt ETF"]] },
        { name: "Commodity ETF", subcategories: [...ETF["Commodity ETF"]] },
        {
          name: "International ETF",
          subcategories: [...ETF["International ETF"]],
        },
        { name: "Sectoral ETF", subcategories: [...INDEX["Equity Index"].Sectoral] },
        { name: "Thematic ETF", subcategories: [...INDEX["Equity Index"].Thematic] },
      ],
    },
    {
      name: "BOND",
      sectorRequired: false,
      industryRequired: false,
      amcRequired: false,
      categories: [
        { name: "Government", subcategories: [...BOND.Government] },
        { name: "Corporate", subcategories: [...BOND.Corporate] },
        { name: "Municipal", subcategories: [...BOND.Municipal] },
        { name: "PSU", subcategories: [...BOND.PSU] },
        { name: "International", subcategories: [...BOND.International] },
      ],
    },
    {
      name: "INDEX",
      sectorRequired: false,
      industryRequired: false,
      amcRequired: false,
      categories: [
        { 
          name: "Equity Index", 
          subcategories: ["BroadMarket", "LargeCap", "MidCap", "SmallCap", "Sectoral", "Thematic"],
          indexNames: INDEX["Equity Index"]
        },
        { name: "Bond Index", subcategories: [...INDEX["Bond Index"]] },
        {
          name: "Commodity Index",
          subcategories: [...INDEX["Commodity Index"]],
        },
        {
          name: "International Index",
          subcategories: [...INDEX["International Index"]],
        },
      ],
    },
  ],

  sectors: [
    { name: "Basic Materials", industries: [...SECTORS["Basic Materials"]] },
    {
      name: "Consumer Cyclical",
      industries: [...SECTORS["Consumer Cyclical"]],
    },
    {
      name: "Consumer Defensive",
      industries: [...SECTORS["Consumer Defensive"]],
    },
    { name: "Energy", industries: [...SECTORS.Energy] },
    {
      name: "Financial Services",
      industries: [...SECTORS["Financial Services"]],
    },
    { name: "Healthcare", industries: [...SECTORS.Healthcare] },
    { name: "Industrials", industries: [...SECTORS.Industrials] },
    { name: "Real Estate", industries: [...SECTORS["Real Estate"]] },
    { name: "Technology", industries: [...SECTORS.Technology] },
    {
      name: "Communication Services",
      industries: [...SECTORS["Communication Services"]],
    },
    { name: "Utilities", industries: [...SECTORS.Utilities] },
  ],

  amcs: [...AMCs],
};

module.exports = financialData;